### ISSUE TITLE
Plane Crazy

### ISSUE THREAD

**Issue by konL445** [o7-Fire/Roblox-4#2]
Can you Make Motor 2 flaps mouse Controlled like in War thunder👍

**Comment by NexitySecond** [comment]
sure

**Comment by NexityThird** [comment]
you can normally do it with normal motor 2 no need exttra stuff

**Comment by NexityThird** [comment]
![993d41b63695559eab787a8e6de7bf09](https://user-images.githubusercontent.com/89519788/148766842-67f1379a-57ed-480f-9473-e44335ed67fc.png)
