### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by phyouthcenter1** [o7-Fire/Roblox-4#7]
Where do I download it and where is main.py

(Render my own video for Plane Crazy)

[Here](https://github.com/o7-Fire/Roblox-4/tree/main/lf-prototype)

**Comment by Itzbenz** [comment]
![image](https://user-images.githubusercontent.com/49940811/169633858-7ea1be7a-59ae-467d-bf12-10a4a6ba520e.png)

**Comment by phyouthcenter1** [comment]
I know that. I did that. I dont have main.py.

**Comment by Itzbenz** [comment]
@NexitySecond

**Comment by shadow01148** [comment]
![image](https://user-images.githubusercontent.com/76457846/169729268-18dc3848-a932-481a-bfa6-983f251a7f51.png)
pretty sure it the py file

**Comment by Itzbenz** [comment]
no

**Comment by shadow01148** [comment]
wym

**Comment by Itzbenz** [comment]
`main.py` is `if-prototype-tool.py`

**Comment by shadow01148** [comment]
miss the part where that my problem

**Comment by Itzbenz** [comment]
but nexity move it

**Comment by Itzbenz** [comment]
Nexity didn't respond/died

**Comment by phyouthcenter1** [comment]
oh ok
